name: Update AI Tools Dataset

on:
  schedule:
    - cron: '0 3 * * *'   # daily at 03:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true   # allows push using GITHUB_TOKEN

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push safely
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add ai_tools.json
          # Commit only if there are changes
          git diff-index --quiet HEAD || git commit -m "Update dataset"
          # Pull remote first to avoid non-fast-forward errors
          git pull origin main --rebase || echo "Nothing to rebase"
          # Push changes
          git push origin HEAD:main
